### ISSUE TITLE
Connection with C++ socket.io client error

### ISSUE THREAD

**Issue by daohuuthao** [mrniko/netty-socketio#394] opened 2016-08-25 10:45 UTC
I'm test with socket.io javascript is OK,
but when i connect with C++ client ( i use cocos2dx lib), I get error :(
( My C++ client work good with server nodejs use socket.io 1.4.5 )

[nioEventLoopGroup-3-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

**java.lang.NumberFormatException: For input string: "true"**
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.valueOf(Integer.java:766)
    **at com.corundumstudio.socketio.transport.PollingTransport.channelRead(PollingTransport.java:91)**
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at com.corundumstudio.socketio.handler.AuthorizeHandler.channelRead(AuthorizeHandler.java:134)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment] 2016-08-25 11:12
Could you please provide a working test case for this? Because I don't have ability to test it with C++

**Comment by daohuuthao** [comment] 2016-08-25 12:08
I have a server developed by nodejs with socket.io 1.4.5,
i'm trying to convert my server to netty-socketio 1.7.11
When i done some feature, i test with web client, with socket.io ---> it's work well with all feature : connect/ disconnect/ event, broadcast ...
But when i use my C++ client, i get error when connect to server.
I'm try read in C++ lib and see : 
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/network/SocketIO.cpp

    pre << "http://" << _uri << "/socket.io/1/?EIO=2&transport=polling&**b64=true**";
but, in java when read b64 use Integer type : 

 List<String> b64 = queryDecoder.parameters().get("b64");
...
if (b64 != null && b64.get(0) != null) {
                    **Integer enable = Integer.valueOf(b64.get(0));**  --> this throw exception :( 
                    ctx.channel().attr(EncoderHandler.B64).set(enable == 1);
                }

I don't know i need change lib in cocos2d-x framework or add try catch in this to work,
because both libs I also use binary version :(

Thanks for listening and support!!! 👍

**Comment by mrniko** [comment] 2016-08-25 12:15
You can fix it like this:

```java
if (b64 != null && b64.get(0) != null) {
String flag = b64.get(0);
if ("true".equals(flag)) {
    flag = "1";
}
Integer enable = Integer.valueOf(b64.get(0));
ctx.channel().attr(EncoderHandler.B64).set(enable == 1);
}
```

And make a pull request to project. I'll accept it

**Comment by daohuuthao** [comment] 2016-08-25 12:18
Could you update it in next version, please.
Now i using binary version by marven :(

**Comment by mrniko** [comment] 2016-08-25 12:33
Of course I can. Could you test it and create a pull request with this change ?

**Comment by daohuuthao** [comment] 2016-08-25 14:04
I tried use source code in git and fix this error.
But it raise other error :(
I trying to debug, but not success:

**[nioEventLoopGroup-3-4] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.**

 // first connection
                        **ClientHead client = ctx.channel().attr(ClientHead.CLIENT).get();**
                        handleMessage(req, client.getSessionId(), queryDecoder, ctx)
**---> this client is null and client.getSessionId() will through null pointer exception.**

**Comment by mrniko** [comment] 2016-08-25 14:34
I think the sequence of messages should be the same as for socketio.js lib. Maybe the problem is in params or message format sent by C++ lib.

**Comment by daohuuthao** [comment] 2016-08-26 05:52
I found something:
in C++ lib: 
origin --> error 
   pre << "http://" << _uri << "**/socket.io/1/?**EIO=2&transport=polling&b64=true";
i chaneg to : ( remove /1/ in path)
    pre << "http://" << _uri << "**/socket.io/?**EIO=2&transport=polling&b64=1";
and 
           s << _uri << "/socket.io/1/websocket/?EIO=2&transport=websocket&sid=" << _sid;
change to 
            s << _uri << "/socket.io/?EIO=3&transport=websocket&sid=" << _sid;
====> I connected success to netty socketio,but it close immediately with out error :( 
( and connect to nodejs server still OK :( )

I trying to continue fix

**Comment by matrixtk** [comment] 2016-09-10 13:36
Any update of this? 
I have the same problem, finally I degraded the netty-socketio version from 1.7.7 to 1.6.6 ( socket.io <0.9 ?), it seems the handshake exception is sovled.

**Comment by kevinho** [comment] 2016-12-19 13:54
Any update on this?
i am using 1.6.6, this problem solved, but that won't be the best choice~

**Comment by vonway** [comment] 2018-01-20 05:33
pr #511  submitted.

**Comment by mrniko** [comment] 2018-01-22 06:27
Fixed by @vonway

**Closed by mrniko** 2018-01-22 06:27 UTC
Labels: bug

**Comment by chenjisi-git** [comment] 2019-01-03 02:21
> I think the sequence of messages should be the same as for socketio.js lib. Maybe the problem is in params or message format sent by C++ lib.

can you fixed it?

**Comment by pablojr** [comment] 2019-01-03 14:07
> Maybe the problem is in params or message format sent by C++ lib.

> can you fixed it?

It looks like that fix should be out of scope for netty-socketio server. You may need to check with the developers of such C++ library
