### ISSUE TITLE
can't connect to socketio server after a few days running (Question)

### ISSUE THREAD

**Issue by rachelxj** [mrniko/netty-socketio#311] opened 2016-01-17 02:18 UTC
I start a netty socketio 1.6.7 server on ubuntu, I've set max number of open file on linux to a large number. But after a few days running, it shows can't access http://serverIP:9092/socket.io/1?xxxx. I checked the client number which connect to port 9092, it's less than 4000. I couldn't identify where the problem is, there is no error log. Is there any connection limits on a single server?

**Comment by mrniko** [comment] 2016-01-17 08:50
I think it's a problem with `silent channels` - opened channels without any data sent by client during channel initialization this is the cause of hanged channels. This issue fixed in https://github.com/mrniko/netty-socketio/commit/ac509898d2d809a077a645e5b4708f41cdd011bc so please build `1.6` branch

**Comment by rachelxj** [comment] 2016-01-19 00:30
thanks, so this fix hasn't been released yet, right? I'll try the branch.

**Comment by rachelxj** [comment] 2016-01-19 00:38
one more question, any idea about the maximum clients the server can maintain the connections with 2G RAM (I ran it on EC2)?

**Comment by mrniko** [comment] 2016-01-19 15:07
> thanks, so this fix hasn't been released yet, right?

Yea!

> one more question, any idea about the maximum clients the server can maintain the connections with 2G RAM (I ran it on EC2)?

I have test results for previous netty-socketio version made four years ago. 
There was follow sessions amount with 4GB RAM - 6000 xhr-long polling sessions OR 15000 websockets sessions and 4000 msg/sec.

**Closed** 2016-01-20 01:40 UTC
